### ISSUE TITLE
az

### ISSUE THREAD

**Issue by diyanqi** [programerTobyLai/TobyPyOnline#1]
这怎么实现的啊QWQ
---
什么原理

**Comment by tobylaifun** [comment]
sculpt 一个js端实现的python，和海龟编辑器在线版原理一样
另外给你看个win11？
https://view.email.microsoftemail.com/?qs=d2acacc95447ebcd95644038971d5e40a523ba82199b5efae545d729f4d82a6e92afa1b962a62f1aacd6ce5d1bffeecc976c302937a372f48bf37e32cdb503aa63543d8b33705962dd555aaf184d16a7eaa563299300123e


ACstudioToby 
On 7/2/2021 ***@***.***> wrote：

这怎么实现的啊QWQ

什么原理

**Comment by diyanqi** [comment]
oo
